server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
    - url: https://ipfran.ru/
      name: Ipfran.Ru
    - url: http://www.playback.ru/
      name: PlayBack.Ru

jsoup-connect:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com